# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.IntegerField()),
                ('css', models.IntegerField()),
                ('javascript', models.IntegerField()),
                ('python', models.IntegerField()),
                ('django', models.IntegerField()),
                ('iosDevelopment', models.IntegerField()),
                ('androidDevelopment', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
            ],
        ),
    ]
