# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meuscandidatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkills',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='meuscandidatos.User')),
                ('html', models.IntegerField()),
                ('css', models.IntegerField()),
                ('javascript', models.IntegerField()),
                ('python', models.IntegerField()),
                ('django', models.IntegerField()),
                ('iosDevelopment', models.IntegerField()),
                ('androidDevelopment', models.IntegerField()),
            ],
            bases=('meuscandidatos.user',),
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
