# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuscandidatos', '0004_auto_20171004_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='androidDevelopment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='css',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='django',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='html',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='iosDevelopment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='javascript',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userskills',
            name='python',
            field=models.PositiveIntegerField(),
        ),
    ]
