# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 19:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuscandidatos', '0008_auto_20171004_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='E-mail inválido')]),
        ),
    ]
